Replace webpack with vite
toggle-corp/miti-web pull request #5
Opened 2024-06-04 16:57 UTC by frozenhelium

### TODO

- [ ] Add navbar
- [ ] Add footer
- [ ] Update components
- [ ] Update data

2024-06-05 04:17 UTC, AdityaKhatri approved these changes

2024-06-06 12:30 UTC, tnagorra commented on src/components/Calendar/Header/index.tsx
> +    );
Let's remove this

2024-06-06 12:31 UTC, tnagorra commented on src/components/Calendar/index.tsx
> +        const todayDate = EnglishDate.fromNativeDate(new Date(2020, 1, 1)).toNepaliDate();
Let's add FIXME

2024-06-06 12:33 UTC, tnagorra requested changes
Looks good for now!

2024-06-12 08:54 UTC, merged